movie_app/urls.py
from . import views
from django.urls import path
from .views import ShowAllDirectors, ShowAllActors, ShowOneDirector, ShowOneActor

urlpatterns = [
    path('', views.show_all_movie),
    path('movie/<slug:slug_movie>', views.show_one_movie, name='movie-detail'),
    path('directors', ShowAllDirectors.as_view()),
    path('directors/<int:pk>', ShowOneDirector.as_view(), name='director-detail'),
    path('actors', ShowAllActors.as_view()),
    path('actors/<int:pk>', ShowOneActor.as_view(), name='actor-detail')

]

movie_proj/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Наша админка"
admin.site.index_title = "Моя админка"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls')),
    path('__debug__/', include('debug_toolbar.urls'))

]

movie_app/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class DressingRoom(models.Model):
    floor = models.IntegerField()
    number = models.IntegerField()

    def __str__(self):
        return f'{self.floor} {self.number}'

class Actor(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDERS = [
        (MALE, 'Мужчина'),
        (FEMALE, 'Женщина')
    ]
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDERS, default=MALE)
    dressing = models.OneToOneField(DressingRoom, on_delete=models.SET_NULL, null=True, blank=True)


    def get_url(self):
        return reverse('actor-detail', args=[self.id])

    def __str__(self):
        if self.gender == self.MALE:
            return f'Актер {self.first_name} {self.last_name}'
        else:
            return f'Актриса {self.first_name} {self.last_name}'

class Director(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    director_email = models.EmailField()

    def get_url(self):
        return reverse('director-detail', args=[self.id])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Movie(models.Model):
    EURO = 'EUR'
    USD = 'USD'
    RUB = 'RUB'

    СURRENCY_CHOICES = [
        (EURO, 'Euro'),
        (USD, 'Dollars'),
        (RUB, 'Rubles')
    ]

    name = models.CharField(max_length=40)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    year = models.IntegerField(null=True, blank=True)
    budget = models.IntegerField(default=1000000, validators=[MinValueValidator(1)])
    currency = models.CharField(max_length=3, choices=СURRENCY_CHOICES, default=RUB)
    slug = models.SlugField(default="", null=False)
    director = models.ForeignKey(Director, on_delete=models.PROTECT, null=True, related_name='movies')
    actors = models.ManyToManyField(Actor)

    '''def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Movie, self).save(*args, **kwargs)'''

    def get_url(self):
        return reverse('movie-detail', args=[self.slug])

    def __str__(self):
        return f'{self.name} - {self.rating}%'

movie_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Movie, Director, Actor
from django.db.models import F, Sum, Max, Min, Count, Avg, Value
from django.views.generic import ListView, DetailView


# Create your views here.

def show_all_movie(request):
    # movies = Movie.objects.order_by('-rating')
    movies = Movie.objects.annotate(
        true_bool=Value(True),
        false_bool=Value(False),
        str_field=Value('hello'),
        new_budget=F('budget') + 100,
    )
    agg = movies.aggregate(Avg('budget'), Max('rating'), Min('rating'), Count('name'))
    return render(request, 'movie_app/all_movies.html',
                  {'movies': movies,
                   'agg': agg
                   })


def show_one_movie(request, slug_movie: str):
    movie = get_object_or_404(Movie, slug=slug_movie)
    return render(request, 'movie_app/one_movie.html', {'movie': movie})

'''
def show_all_directors(request):
    directors = Director.objects.all
    return render(request, 'movie_app/all_directors.html', {'directors': directors})'''

class ShowAllDirectors(ListView):
    template_name = 'movie_app/all_directors.html'
    model = Director
    context_object_name = 'directors'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

class ShowOneDirector(DetailView):
    template_name = 'movie_app/one_director.html'
    model = Director
    context_object_name = 'director'


class ShowOneActor(DetailView):
    template_name = 'movie_app/one_actor.html'
    model = Actor
    context_object_name = 'actor'


'''

def show_one_director(request, id_director: int):
    director = get_object_or_404(Director, id=id_director)
    return render(request, 'movie_app/one_director.html', {'director': director})


def show_all_actors(request):
    actors = Actor.objects.all
    return render(request, 'movie_app/all_actors.html', {'actors': actors})'''

class ShowAllActors(ListView):
    template_name = 'movie_app/all_actors.html'
    model = Actor
    context_object_name = 'actors'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

'''
def show_one_actor(request, id_actor: int):
    actor = get_object_or_404(Actor, id=id_actor)
    return render(request, 'movie_app/one_actor.html', {'actor': actor})'''

movie_app/templates/movie_app/all_actors.html
{% extends 'movie_app/base.html' %}

{% block title %} Все актеры {% endblock %}

{% block content %}

    <h2>Список всех актеров</h2>
        <ul>
            {% for actor in actors %}
            <li>
                <a href="{{ actor.get_url }}">
                    {% if actor.gender == 'F' %}
                        Актриса {{actor.first_name}} {{actor.last_name}}
                    {% else %}
                        Актер {{actor.first_name}} {{actor.last_name}}
                    {% endif %}
                </a>
            </li>
            {% endfor %}
        </ul>

{% endblock %}

movie_app/templates/movie_app/all_directors.html
{% extends 'movie_app/base.html' %}

{% block title %} Все режиссеры {% endblock %}

{% block content %}

    <h2>Список всех Режиссеров</h2>
        <ul>
            {% for director in directors %}
            <li>
                <a href="{{ director.get_url }}">{{director.first_name}} {{director.last_name}}</a>
            </li>
            {% endfor %}
        </ul>

{% endblock %}

movie_app/templates/movie_app/all_movies.html
{% extends 'movie_app/base.html' %}

{% block title %} Все фильмы {% endblock %}

{% block content %}

    <h2>Список всех фильмов</h2>
        <ul>
            {% for movie in movies %}
                 <li><a href="{{ movie.get_url }}">{{ movie.name }}</a>,
                     рейтинг - {{ movie.rating }},
                     год - {{ movie.year|default:"Неизвестен" }},
                     бюджет - {{ movie.budget }},
                     скорректированный бюджет - {{ movie.new_budget }}
                 </li>
            {% endfor %}
        </ul>
    <h3>Средний бюджет - {{ agg.budget__avg }}</h3>
    <h3>Минимальный рейтинг - {{ agg.rating__min }}</h3>
    <h3>Максимальный рейтинг - {{ agg.rating__max }}</h3>
    <h3>Всего фильмов - {{ agg.name__count}}</h3>
{% endblock %}

movie_app/templates/movie_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

movie_app/templates/movie_app/one_actor.html
{% extends 'movie_app/base.html' %}

{% block title %} Информация об актере - {{ actor.first_name }} {{ actor.last_name }}{% endblock %}

{% block content %}

    <h2>Актер</h2>
    <h3>Имя - {{ actor.first_name }}</h3>
    <h3>Фамилия - {{ actor.last_name }}</h3>
    <h3>Пол - {{ actor.gender }}</h3>
       <hr>
    <h3>Список фильмов</h3>
            <ul>
            {% for movie in actor.movie_set.all %}
                 <li>{{ movie }}
                 </li>
            {% endfor %}
        </ul>

{% endblock %}

movie_app/templates/movie_app/one_director.html
{% extends 'movie_app/base.html' %}

{% block title %} Информация о режиссере - {{ object.first_name }} {{ object.last_name }}{% endblock %}

{% block content %}

    <h2>Режиссер</h2>
    <h3>Имя - {{ object.first_name }}</h3>
    <h3>Фамилия - {{ object.last_name }}</h3>
    <h3>Почта - {{ object.director_email }}</h3>
    <hr>
    <h3>Список фильмов</h3>
            <ul>
            {% for movie in director.movies.all %}
                 <li>{{ movie }}
                 </li>
            {% endfor %}
        </ul>


{% endblock %}

movie_app/templates/movie_app/one_movie.html
{% extends 'movie_app/base.html' %}

{% block title %} Информация о фильме - {{ movie.name }}{% endblock %}

{% block content %}

    <h2>Информация о фильме - {{ movie.name }}</h2>
    <h3>Рейтинг {{ movie.rating }}</h3>
    <h3>Бюджет {{ movie.budget }}</h3>
    <h3>Год выхода {{ movie.year }}</h3>
    <hr>
    <h3>Информация о Режиссере</h3>
    <h3>Имя {{ movie.director.first_name }}</h3>
    <h3>Фамилия {{ movie.director.last_name }}</h3>
    <h3>Почта {{ movie.director.director_email }}</h3>
    <hr>
    <h3>Список актеров</h3>
        <ul>
            {% for actor in movie.actors.all %}
                 <li>{{ actor }}
                 </li>
            {% endfor %}
        </ul>


{% endblock %}